In [40]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter

import re
import os
import sys

sys.path.append(os.path.abspath('../'))

In [41]:
raw_path = "../data/raw/"
processed_path = "../data/processed/"
figures_path= "../reports/figures/"
src_path = "../src/"

In [42]:
# Load dữ liệu
df_listings = pd.read_csv(os.path.join(processed_path, 'df_listings_cleaned.csv'))
df_occupancy = pd.read_csv(os.path.join(processed_path, 'df_occupancy.csv'))

In [43]:
df_listings.rename(columns={'id': 'listing_id'}, inplace=True)

In [44]:
df_airbnbCambridge = pd.merge(df_listings, df_occupancy, left_on='listing_id', right_on='listing_id', how='inner')

In [46]:
df_airbnbCambridge.to_csv('../data/processed/df_airbnbCambridge.csv', index=False)

In [48]:
df_airbnbCambridge.head()

,listing_id,host_is_superhost,host_listings_count,host_total_listings_count,neighbourhood_cleansed,latitude,longitude,accommodates,bedrooms,beds,...,has_kitchen,has_hair_dryer,has_refrigerator,amenities_count,property_type_Hotel_B_and_B,property_type_House,property_type_Other_Unique,has_license,has_review,occupancy_rate
0,8521,1,2,3,West Cambridge,42.38258,-71.13646,5,2.0,2.0,...,1,0,1,46,0,0,0,1,1,0.257534
1,11169,1,4,4,North Cambridge,42.39630,-71.13135,3,1.0,0.0,...,0,1,1,27,0,0,0,0,1,0.852055
2,19581,1,3,3,The Port,42.36258,-71.09603,1,1.0,1.0,...,1,1,1,46,1,0,0,0,1,0.805479
3,27498,1,3,3,The Port,42.36254,-71.09698,2,1.0,1.0,...,1,1,1,50,1,0,0,0,1,0.934247
4,79762,1,1,2,The Port,42.36950,-71.09921,4,2.0,2.0,...,1,1,1,30,0,0,0,1,1,0.824658

In [49]:
df_airbnbCambridge.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1055 entries, 0 to 1054
Data columns (total 43 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   listing_id                      1055 non-null   int64
 1   host_is_superhost               1055 non-null   int64
 2   host_listings_count             1055 non-null   int64
 3   host_total_listings_count       1055 non-null   int64
 4   neighbourhood_cleansed          1055 non-null   object
 5   latitude                        1055 non-null   float64
 6   longitude                       1055 non-null   float64
 7   accommodates                    1055 non-null   int64
 8   bedrooms                        1055 non-null   float64
 9   beds                            1055 non-null   float64
 10  price                           1055 non-null   float64
 11  minimum_nights                  1055 non-null   int64
 12  maximum_nights                  1055 non-null   int64
 13  review_scores_rating            1055 non-null   float64
 14  review_scores_accuracy          1055 non-null   float64
 15  review_scores_cleanliness       1055 non-null   float64
 16  review_scores_checkin           1055 non-null   float64
 17  review_scores_communication     1055 non-null   float64
 18  review_scores_location          1055 non-null   float64
 19  review_scores_value             1055 non-null   float64
 20  instant_bookable                1055 non-null   int64
 21  calculated_host_listings_count  1055 non-null   int64
 22  bath_qty                        1055 non-null   float64
 23  is_shared_bath                  1055 non-null   float64
 24  room_type_Hotel room            1055 non-null   bool
 25  room_type_Private room          1055 non-null   bool
 26  has_smoke_alarm                 1055 non-null   int64
 27  has_carbon_monoxide_alarm       1055 non-null   int64
 28  has_wifi                        1055 non-null   int64
 29  has_hot_water                   1055 non-null   int64
 30  has_hangers                     1055 non-null   int64
 31  has_essentials                  1055 non-null   int64
 32  has_bed_linens                  1055 non-null   int64
 33  has_kitchen                     1055 non-null   int64
 34  has_hair_dryer                  1055 non-null   int64
 35  has_refrigerator                1055 non-null   int64
 36  amenities_count                 1055 non-null   int64
 37  property_type_Hotel_B_and_B     1055 non-null   int64
 38  property_type_House             1055 non-null   int64
 39  property_type_Other_Unique      1055 non-null   int64
 40  has_license                     1055 non-null   int64
 41  has_review                      1055 non-null   int64
 42  occupancy_rate                  1055 non-null   float64
dtypes: bool(2), float64(15), int64(25), object(1)
memory usage: 340.1+ KB

In [50]:
df_airbnbCambridge.isnull().sum()

listing_id                        0
host_is_superhost                 0
host_listings_count               0
host_total_listings_count         0
neighbourhood_cleansed            0
latitude                          0
longitude                         0
accommodates                      0
bedrooms                          0
beds                              0
price                             0
minimum_nights                    0
maximum_nights                    0
review_scores_rating              0
review_scores_accuracy            0
review_scores_cleanliness         0
review_scores_checkin             0
review_scores_communication       0
review_scores_location            0
review_scores_value               0
instant_bookable                  0
calculated_host_listings_count    0
bath_qty                          0
is_shared_bath                    0
room_type_Hotel room              0
room_type_Private room            0
has_smoke_alarm                   0
has_carbon_monoxide_alarm         0
has_wifi                          0
has_hot_water                     0
has_hangers                       0
has_essentials                    0
has_bed_linens                    0
has_kitchen                       0
has_hair_dryer                    0
has_refrigerator                  0
amenities_count                   0
property_type_Hotel_B_and_B       0
property_type_House               0
property_type_Other_Unique        0
has_license                       0
has_review                        0
occupancy_rate                    0
dtype: int64

In [51]:
df_airbnbCambridge.describe()

,listing_id,host_is_superhost,host_listings_count,host_total_listings_count,latitude,longitude,accommodates,bedrooms,beds,price,...,has_kitchen,has_hair_dryer,has_refrigerator,amenities_count,property_type_Hotel_B_and_B,property_type_House,property_type_Other_Unique,has_license,has_review,occupancy_rate
count,1.055000e+03,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,...,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000,1055.000000
mean,6.427799e+17,0.375355,684.121327,818.099526,42.373291,-71.105369,3.401896,1.518483,1.880569,1186.094787,...,0.829384,0.795261,0.820853,35.502370,0.088152,0.208531,0.015166,0.340284,0.803791,0.590116
std,5.618361e+17,0.484444,1677.561389,1934.157286,0.010044,0.018463,2.377072,0.959023,1.480727,6211.421226,...,0.376352,0.403702,0.383657,14.924343,0.283650,0.406451,0.122270,0.474029,0.397316,0.281152
min,8.521000e+03,0.000000,1.000000,1.000000,42.353670,-71.155510,1.000000,0.000000,0.000000,29.000000,...,0.000000,0.000000,0.000000,4.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,3.928464e+07,0.000000,3.000000,4.000000,42.366240,-71.117936,2.000000,1.000000,1.000000,105.000000,...,1.000000,1.000000,1.000000,27.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.358904
50%,7.081508e+17,0.000000,15.000000,24.000000,42.370570,-71.104490,2.000000,1.000000,1.000000,204.000000,...,1.000000,1.000000,1.000000,33.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.621918
75%,1.152620e+18,1.000000,169.000000,234.000000,42.380366,-71.090755,4.000000,2.000000,2.000000,322.000000,...,1.000000,1.000000,1.000000,42.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.832877
max,1.517698e+18,1.000000,5143.000000,5933.000000,42.400180,-71.071239,16.000000,8.000000,9.000000,50031.000000,...,1.000000,1.000000,1.000000,103.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000