In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from collections import Counter
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error, mean_absolute_error, r2_score

import re
import os
import sys

sys.path.append(os.path.abspath('../'))

In [3]:
file_path = '../data/processed/X_train_scaled.csv'
X_train_scaled = pd.read_csv(file_path)

file_path1 = '../data/processed/X_test_scaled.csv'
X_test_scaled = pd.read_csv(file_path1)

file_path2 = '../data/processed/y_train.csv'
y_train = pd.read_csv(file_path2)

file_path3 = '../data/processed/y_test.csv'
y_test = pd.read_csv(file_path3)

In [6]:
# Khởi tạo mô hình và học
lr_model = LinearRegression()
lr_model.fit(X_train_scaled, y_train)

# thử trên tập test
lr_preds = lr_model.predict(X_test_scaled)
r2_lr = r2_score(y_test, lr_preds)
rmse_lr = np.sqrt(mean_squared_error(y_test, lr_preds))
mae_lr = mean_absolute_error(y_test, lr_preds)

print(f"R^2 (Độ chính xác): {r2_lr:.4f}")
print(f"RMSE (Trung bình): ${rmse_lr:.2f}")
print(f"MAE (Tuyệt đối): ${mae_lr:.2f}")

R^2 (Độ chính xác): 0.4392
RMSE (Trung bình): $115.81
MAE (Tuyệt đối): $79.09

In [9]:
coefficients = pd.DataFrame({
    'Feature': X_train_scaled.columns,
    'Mức độ tác động giá': lr_model.coef_.flatten()
}).sort_values(by='Mức độ tác động giá', ascending=False)

display(coefficients.head(5))

display(coefficients.tail(5))

                                  Feature  Mức độ tác động giá
1                            accommodates            76.696836
22                        amenities_count            28.780158
23            property_type_Hotel_B_and_B            26.308372
7          calculated_host_listings_count            25.198880
32  neighbourhood_cleansed_East Cambridge            21.549213

                                   Feature  Mức độ tác động giá
35  neighbourhood_cleansed_North Cambridge           -15.103184
13               has_carbon_monoxide_alarm           -17.876318
27                              has_review           -26.604501
11                  room_type_Private room           -26.865172
16                             has_hangers           -28.475357